version: '3'
services:

  soundcloud.frontend.public:
    build:
      dockerfile: Dockerfile
      context: ./frontend/public
    container_name: soundcloud.frontend.public
    volumes:
      - ./frontend/public/src:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - soundcloud.api
    networks:
      - sound_net

  soundcloud.api:
    build:
      dockerfile: Dockerfile
      context: ./backend/api
    container_name: soundcloud.api
    depends_on:
      - soundcloud.db.mysql.main
      - soundcloud.storage.minio
    ports:
      - "8080:8080"

  soundcloud.websocket.messenger:
    build:
      dockerfile: Dockerfile
      context: ./backend/websocket-messenger
    container_name: soundcloud.websocket.messenger
    depends_on:
      - soundcloud.db.mysql.main
      - soundcloud.storage.minio
    ports:
      - "8081:8081"

  soundcloud.db.mysql.main:
    build:
      dockerfile: Dockerfile
      context: ./services/mysql
    container_name: soundcloud.db.mysql.main
    volumes:
      - ./volumes/db/mysql/soundcloud/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - sound_net

  soundcloud.storage.minio:
    build:
      dockerfile: Dockerfile
      context: ./services/minio
    container_name: soundcloud.storage.minio
    volumes:
      - ./volumes/storage/minio/soundcloud:/var/lib/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sound_net

  soundcloud.rabbit.mq:
    build:
      dockerfile: Dockerfile
      context: ./services/rabbitmq
    container_name: soundcloud.rabbit.mq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  soundcloud.nginx.router:
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - soundcloud.api
      - soundcloud.db.mysql.main
    networks:
      - sound_net

networks:
  sound_net:
    driver: bridge