version: '3'
services:

  frontend.public:
    build:
      dockerfile: Dockerfile
      context: ./frontend/public
    container_name: frontend.public
    volumes:
      - ./frontend/public/src:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - soundcloud.api
    networks:
      - sound_net

  soundcloud.api:
    build:
      dockerfile: Dockerfile
      context: ./backend/api
    container_name: soundcloud.api
    depends_on:
      - db.mysql.soundcloud.main
      - storage.minio.soundcloud
    ports:
      - "8080:8080"


  db.mysql.soundcloud.main:
    build:
      dockerfile: Dockerfile
      context: ./services/mysql
    container_name: db.mysql.soundcloud.main
    volumes:
      - ./volumes/db/mysql/soundcloud/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - sound_net

  storage.minio.soundcloud:
    build:
      dockerfile: Dockerfile
      context: ./services/minio
    container_name: storage.minio.soundcloud
    volumes:
      - ./volumes/storage/minio/soundcloud:/var/lib/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sound_net

  nginx.router:
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - soundcloud.api
      - db.mysql.soundcloud.main
    networks:
      - sound_net

networks:
  sound_net:
    driver: bridge